### ISSUE TITLE
"Logout" not working

### ISSUE THREAD

**Issue by venelouis** [LinkedInLearning/django-esst-2894047#6]
## Issue Overview

After finishing the entire course, everything worked perfectly well, except the "logout" part, when you try to click the "logut" button or type in the address bar: "/logout". I get the error in terminal:

Method Not Allowed (GET): /logout
Method Not Allowed: /logout
[21/Jan/2024 15:46:49] "GET /logout HTTP/1.1" 405 0

I'm using Django 5 and Python 11. I would like to know if there is a solution to this problem.

## Describe your environment

I'm using Django 5.0.1 and Python 3.10.12 Brave browser.

## Steps to Reproduce

1. I just reproduced exacly what is in the course: [https://github.com/venelouis/Django-Essential-Training/tree/last/django5](https://github.com/venelouis/Django-Essential-Training/tree/last/django5)

## Expected Behavior

See the logout page

## Current Behavior

HTTP ERROR 405

## Screenshots / Video

![Screenshot at 2024-01-21 15-19-45](https://github.com/LinkedInLearning/django-esst-2894047/assets/37526748/52e66e7a-29af-44e5-a608-3744a202fde5)
![Screenshot at 2024-01-21 15-21-52](https://github.com/LinkedInLearning/django-esst-2894047/assets/37526748/390d2c5f-55d6-48ca-b516-ca57d20c1167)

## Related Issues

Method Not Allowed (GET): /logout
Method Not Allowed: /logout
[21/Jan/2024 15:46:49] "GET /logout HTTP/1.1" 405 0

**Comment by leportella** [comment]
Hi! Sorry about that. 

Indeed there's a problem with the logout. The reason is that [Django is no longer supporting a logout](https://docs.djangoproject.com/en/dev/releases/4.1/#log-out-via-get) based on a GET that is what we have in our class. 

The way to fix it is to transform the link to Logout from a GET to a POST, this is, from a simple link redirect to an actual post:

```python
         <form id="logout-form" method="post" class="d-inline" action="{% url 'logout' %}">
          {% csrf_token %}
         <button class="btn btn-outline-light me-1" type="submit">New logout</button>
         </form>
```

This will do 2 things: make a POST request when a user clicks there, and will transform this form into a button, so there will be no change to the user. [Here's the exact diff](https://github.com/LinkedInLearning/django-esst-2894047/commit/87bc59b7223a49078b37e6c26933fa9eeec75607) of what needs to be done

**Comment by leportella** [comment]
Special thanks to Ben Strange that showed me the error and the reason why!

**Comment by venelouis** [comment]
thanks, I will try!
